### PR TITLE
Fix Typo in README.md

### PR DESCRIPTION
**Pull request by mert-kurttutan**
Just noticed while trying out your project

### CODE REVIEW

**Review by valebes — APPROVED** [review]
All ok!
Thanks!!

**Comment by valebes** [comment]
@mert-kurttutan Thanks for your contribution and for trying PPL.
Sorry if I bother you, but I wanted to ask what you think about the available documentation? If you have any suggestions, please let us know.

**Comment by mert-kurttutan** [comment]
I think publishing on crate (and hence providing API documentation from doc.rs) would be great as it provides the most convenient interface for checking out APIs, more convenient than going through source code.

**Comment by mert-kurttutan** [comment]
Also, rust mdbook type website is also popular among Rust Crates, which can be created using github page
and https://github.com/rust-lang/mdBook

**Comment by valebes** [comment]
Thanks for the suggestions. I surely look to publish it on crates.io. For the examples + guide I think is a good suggestion the one to use mdBook

**Pull request merged**
